Models/Teamowner/Teamow.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel.DataAnnotations;

namespace AD.Models.Teamowner
{
    public class Teamow
    {
        //Attributes
        public int teamow_id { get; set; }

        [Required(ErrorMessage = "Please Enter Team Owner Name !")]
        [Display(Name = "Team Owner Name :")]
        public string teamow_name { get; set; }

        [Required(ErrorMessage = "Please Enter Team Name !")]
        [Display(Name = "Team Name :")]
        public string team_name { get; set; }

        [Required(ErrorMessage = "Please Enter Team owner email !")]
        [Display(Name = "Team Owner Email :")]
        public string teamow_email { get; set; }

        [Required(ErrorMessage = "Please Enter Team owner conatct !")]
        [Display(Name = "Team Owner Contact :")]
        public string teamow_contact { get; set; }


        [Required(ErrorMessage = "Please Enter Team owner Password !")]
        [Display(Name = "Team Owner  Password :")]
        [DataType(DataType.Password)]
        public string password { get; set; }



        [Required(ErrorMessage = "Please Enter RePassword !")]
        [Display(Name = "Re-Password :")]
        [DataType(DataType.Password)]
        [Compare("password")]
        public string repassword { get; set; }

    }
}

Controllers/Admin/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace AD.Controllers.Admin
{
    public class AdminController : Controller
    {
        public ActionResult Login()
        {
            return View();
        }

        public ActionResult Dashboard()
        {
            return View();
        }

        public ActionResult TeamOwner()
        {
            return View();
        }

        // GET: AdminController
        public ActionResult Index()
        {
            return View();
        }

        // GET: AdminController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: AdminController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: AdminController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: AdminController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: AdminController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: AdminController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: AdminController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Controllers/Players/NewPlayersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Data.SqlClient;
using Microsoft.AspNetCore.Mvc;
using AD.Models.Player;
using Microsoft.AspNetCore.Http;
using System.Data;

namespace AD.Controllers.Players
{
    public class NewPlayersController : Controller
    {
        SqlConnection con = new SqlConnection();
        SqlCommand com = new SqlCommand();
        SqlDataReader dr;

        string Str = @"Data Source=LDW-LAP;Initial Catalog=ESPORTS;Integrated Security=True";

        void connectionString()
        {
            con.ConnectionString = "Data Source=LDW-LAP;Initial Catalog=ESPORTS;Integrated Security=True";
        }

        //Player Dashboard
        public IActionResult PlayerDashboard()
        {
            return View();
        }

        //Player Login
        [HttpGet]
        public IActionResult PlayerLogin()
        {
            return View();
        }


        //Player verify
        [HttpPost]
        public IActionResult PlayerLogin(Player plrlog)
        {
            Player obj = new Player(); 
            connectionString();
            con.Open();
            com.Connection = con;
            com.CommandText = "select * from Player where pemail='" + plrlog.pemail + "' and password = '" + plrlog.password + "' ";
            dr = com.ExecuteReader();
            if (dr.Read())
            {
                con.Close();
                return View("PlayerDashboard");
            }
            else
            {
                con.Close();
                ViewData["message"] = "Email or Password incorrect!";
            }
            return View();
        }








        // GET: Player/Create
        [HttpGet]
        public IActionResult PlayerCreate()
        {
            return View(new Player());
        }

        // POST: Player/Create
        [HttpPost]
        public IActionResult PlayerCreate(Player nplayer)
        {
            try
            {
                using (SqlConnection con = new SqlConnection(Str))
                {
                    con.Open();
                    string q = "INSERT INTO Player VALUES ('" + nplayer.pemail + "', '" + nplayer.playename + "', '" + nplayer.password + "', '" + nplayer.age + "' , '" + nplayer.pimg + "', '" + nplayer.bowler_or_batman + "','" + nplayer.battingstyle + "',  '" + nplayer.bowlingstyle + "',  '" + nplayer.mtaches + "',  '" + nplayer.witckets + "', '" + nplayer.runs + "', '" + nplayer.previous_cup + "')";
                    SqlCommand cmd = new SqlCommand(q, con);
                    cmd.ExecuteNonQuery();
                }
                return RedirectToAction("PlayerList");
            }
            catch
            {
                return View();
            }
            
        }


        // GET Player/Registration
        public IActionResult PlayerReg()
        {
            return View();
        }

        // POST Player/Registration
        [HttpPost]
        public IActionResult PlayerReg(Player nplayer, IFormFile file)
        {
            connectionString();
            con.Open();
            com.Connection = con;
            com.CommandText = "INSERT INTO Player (pemail,playename,password,age,pimg,bowler_or_batman,battingstyle,bowlingstyle,mtaches,witckets,runs,previous_cup,thropy,base_price,status) VALUES ('" + nplayer.pemail + "', '" + nplayer.playename + "', '" + nplayer.password + "', '" + nplayer.age + "' , '" + nplayer.pimg + "', '" + nplayer.bowler_or_batman + "','" + nplayer.battingstyle + "',  '" + nplayer.bowlingstyle + "',  '" + nplayer.mtaches + "',  '" + nplayer.witckets + "', '" + nplayer.runs + "', '" + nplayer.previous_cup + "', '" + nplayer.thropy + "',0,0 ) ";
            dr = com.ExecuteReader();
            con.Close();
            ViewData["Message"] = "Player Record  " +  nplayer.playename + "Is Saved Successfully !";
            return View();
        }


        // Player/LIST VIEW
        public IActionResult PlayerList(int id)
        {
            var playerlist = new List<Player>();

            String constr = "Data Source=LDW-LAP;Initial Catalog=ESPORTS;Integrated Security=True";

            using (SqlConnection connection = new SqlConnection(constr))
            {
                connection.Open();
                String sql = "SELECT * FROM Player";

                using (SqlCommand command = new SqlCommand(sql, connection))
                {
                    using (SqlDataReader reader = command.ExecuteReader())
                    {
                        while (reader.Read())
                        {
                            Player plr = new Player();
                            plr.playerID = reader.GetInt32(0);
                            plr.pemail = reader.GetString(1);
                            plr.playename = reader.GetString(2);
                            plr.password = reader.GetString(3);
                            plr.age = reader.GetInt32(4);
                            plr.pimg = reader.GetString(5);
                            plr.bowler_or_batman = reader.GetString(6);
                            plr.battingstyle = reader.GetString(7);
                            plr.bowlingstyle = reader.GetString(8);
                            plr.mtaches = reader.GetInt32(9);
                            plr.witckets = reader.GetInt32(10);
                            plr.runs = reader.GetInt32(11);
                            plr.previous_cup = reader.GetString(12);


                            playerlist.Add(plr);
                        }
                    }
                }
            }

            return View(playerlist);
        }



        //DELETE ACTION 
        public IActionResult PlayerDelete(int player)
        {
            connectionString();
            con.Open();
            string query = "DELETE FROM Player WHERE playerID = @player ";
            SqlCommand cmd = new SqlCommand(query, con);
            cmd.Parameters.AddWithValue("@player", player);
            cmd.ExecuteNonQuery();

            return RedirectToAction("PlayerList");
        }


        // Get: Player/Edit
       
        public IActionResult PlayerEdit(int playerID)
        {
            Player player = new Player();
            DataTable dataTable = new DataTable();
            using (SqlConnection con = new SqlConnection(Str))
            {
                con.Open();
                string q = "SELECT * FROM Player WHERE playerID=" + playerID;
                SqlDataAdapter da = new SqlDataAdapter(q, con);
                da.Fill(dataTable);
            }
            if(dataTable.Rows.Count== 1)
            {
                player.playerID = Convert.ToInt32(dataTable.Rows[0][0].ToString());
                player.pemail = dataTable.Rows[0][1].ToString();
                player.playename = dataTable.Rows[0][2].ToString();
                player.password = dataTable.Rows[0][3].ToString();
                player.age = Convert.ToInt32(dataTable.Rows[0][4].ToString());
                player.bowler_or_batman = dataTable.Rows[0][5].ToString();
                player.battingstyle = dataTable.Rows[0][6].ToString();
                player.bowlingstyle = dataTable.Rows[0][7].ToString();
                player.mtaches = Convert.ToInt32(dataTable.Rows[0][9].ToString());
                player.witckets = Convert.ToInt32(dataTable.Rows[0][10].ToString());
                player.runs = Convert.ToInt32(dataTable.Rows[0][11].ToString());
                player.previous_cup = dataTable.Rows[0][12].ToString();

                return View(player);

            }
            return RedirectToAction("PlayerList");

        }

        // Post: Player/Edit
        [HttpPost]
        public IActionResult PlayerEdit(int playerID, Player plr)
        {
            
                using (SqlConnection con = new SqlConnection(Str))
                {
                    con.Open();
                    string q = "UPDATE Player SET pemail=@pemail,playename=@playename,age=@age,bowler_or_batman=@bowler_or_batman,battingstyle=@battingstyle,bowlingstyle=@bowlingstyle,mtaches=@mtaches,witckets=@witckets,runs=@runs,previous_cup=@previous_cup WHERE playerID=@playerID";
                    SqlCommand cmd = new SqlCommand(q, con);

                    cmd.Parameters.AddWithValue("@playerID", plr.playerID);
                    cmd.Parameters.AddWithValue("@pemail", plr.pemail);
                    cmd.Parameters.AddWithValue("@playename", plr.playename);
                    cmd.Parameters.AddWithValue("@age", plr.age);
                    cmd.Parameters.AddWithValue("@bowler_or_batman", plr.bowler_or_batman);
                    cmd.Parameters.AddWithValue("@battingstyle", plr.battingstyle);
                    cmd.Parameters.AddWithValue("@bowlingstyle", plr.bowlingstyle);
                    cmd.Parameters.AddWithValue("@mtaches", plr.mtaches);
                    cmd.Parameters.AddWithValue("@witckets", plr.witckets);
                    cmd.Parameters.AddWithValue("@runs", plr.runs);
                    cmd.Parameters.AddWithValue("@previous_cup", plr.previous_cup);

                    cmd.ExecuteNonQuery();
                }

                return RedirectToAction("PlayerList");
            
            
        }



        // Player/LIST VIEW
        public IActionResult PlayerWatchList(int id)
        {
            var playerlist = new List<Player>();

            String constr = "Data Source=LDW-LAP;Initial Catalog=ESPORTS;Integrated Security=True";

            using (SqlConnection connection = new SqlConnection(constr))
            {
                connection.Open();
                String sql = "SELECT * FROM Player";

                using (SqlCommand command = new SqlCommand(sql, connection))
                {
                    using (SqlDataReader reader = command.ExecuteReader())
                    {
                        while (reader.Read())
                        {

Views/Admin/Dashboard.cshtml
@{
    ViewData["Title"] = "Dashboard";
}

<nav class="navbar navbar-expand-lg bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">Admin Dashboard</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="#">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="NewPlayers" asp-action="PlayerList">PlayerList</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="TeamOwner">Team Owner</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link disabled">Disabled</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

Views/Admin/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h1>Admin Login</h1>

<input></input>

<input></input>

<button>Login</button>

Views/Admin/Login.cshtml
@{
    ViewData["Title"] = "Login";
}

<!DOCTYPE html>
<html lang="en">
<head>
   <asp:Content ID="Content1" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
 <link rel="stylesheet" href="~/css/adminlogin.css" />
</head>
 


<div class="container mt-5 px-5 py-5">
    <h1 class="text-center mt-5 px-5 py-5">ADMIN LOGIN</h1>
    <div class="row">
         <div class="col-md-3">
             </div>
        <div class="col-md-6">
             <form action="VerifyCredntials" method="post">
        <!-- Email input -->
        <div class="form-outline mb-4">
            <input type="text" name="UserName" id="form2Example1" class="form-control" />
            <label class="form-label text-white" for="form2Example1">Email address</label>
        </div>

        <!-- Password input -->
        <div class="form-outline mb-4">
            <input type="password" name="Password" id="form2Example2" class="form-control" />
            <label class="form-label text-white" for="form2Example2">Password</label>
        </div>

        <!-- Submit button -->
        <input type="submit" value="LOGIN" class="btn btn-success"/>
    </form>
        </div>
    <div class="col-md-3">
        </div>
    </div>
</div>

Views/Admin/TeamOwner.cshtml
@{
    ViewData["Title"] = "TeamOwner";
}

<nav class="navbar navbar-expand-lg bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">Admin Dashboard</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="#">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="TeamOwner">Team Owner</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Pricing</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link disabled">Disabled</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

<h1>TeamOwner</h1>