Models/Admin/AdminLogin.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AD.Models.Admin
{
    public class AdminLogin
    {
        public string UserName { get; set; }
        public string Password { get; set; }
    }
}

Controllers/Admin/AdminLoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using AD.Models.Admin;
using System.Data.SqlClient;
using System.Data.Sql;
using System.Data.SqlClient;

namespace AD.Controllers.Admin
{
    public class AdminLoginController : Controller
    {
        SqlConnection con = new SqlConnection();
        SqlCommand com = new SqlCommand();
        SqlDataReader dr;
        SqlConnection conn = new SqlConnection(@"Data Source=LDW-LAP;Initial Catalog=ESPORTS;Integrated Security=True");

        [HttpGet]
        public IActionResult Login()
        {
            return View();
        }

        void connectionString()
        {
            con.ConnectionString = "Data Source=LDW-LAP;Initial Catalog=ESPORTS;Integrated Security=True";
        }

        [HttpPost]
        public IActionResult VerifyCredntials(AdminLogin adminLogin)
        {
            connectionString();
            con.Open();
            com.Connection = con;
            com.CommandText = "select * from Admin where user_name='" + adminLogin.UserName + "' and password = '" + adminLogin.Password + "' ";
            dr = com.ExecuteReader();
            if (dr.Read())
            {
                con.Close();
                return View("Dashboard");
            }
            else
            {
                con.Close();
                ViewData["message"] = "User Name or Password incorrect!";
            }
            return View("Login");
        }

        public IActionResult Dashboard()
        {
            return View();
        }

        public IActionResult CreateAdmin()
        {
            return View();
        }


        [HttpPost]
        public IActionResult CreateNewAdmin(SignIn signIn)
        {
            Console.WriteLine("SignIn", signIn.UserName, signIn.Email, signIn.Password, signIn.PhoneNumber);
            //return View();
            connectionString();
            con.Open();
            com.Connection = con;
            com.CommandText = "INSERT INTO Admin (user_name, password, email, phone_number) VALUES ('" + signIn.UserName + "', '" + signIn.Password + "', '" + signIn.Email + "', '" + signIn.PhoneNumber + "') ";
            dr = com.ExecuteReader();
            con.Close();
            return View("Dashboard");
            //if (dr.Read())
            //{
            //    con.Close();
            //    return View("Dashboard");
            //}
            //else
            //{
            //    con.Close();
            //    return View("Error");
            //}
            //string query1 = "INSERT INTO Admin (user_name, password, email, phone_number) VALUES ('" + signIn.UserName + "', '" + signIn.Password + "', '" + signIn.Email + "', '" + signIn.PhoneNumber + "') ";
            //SqlCommand cmd1 = new SqlCommand(query1, con);

            //SqlConnection conn = new SqlConnection("Data Source = DESKTOP - ES9JH7P; Initial Catalog = ESPORTS; Integrated Security = True");
            //conn.Open();
            //SqlCommand cmd = new SqlCommand("INSERT INTO Admin (user_name, password, email, phone_number) VALUES ('" + signIn.UserName + "', '" + signIn.Password + "', '" + signIn.Email + "', '" + signIn.PhoneNumber + "') ");
            //cmd.ExecuteNonQuery();

            //return View("Dashboard");
        }

        public IActionResult CreateTrophy()
        {
            return View();
        }

        public IActionResult CreateNewTrophyV1()
        {
            //var t = new List<Trophy>();
            //for(int i = 1; i < 11; i++)
            //{
            //    t.Add(item: new Trophy()
            //    {
            //        Name = "test ${i}",
            //        EndDate = "2022-10",
            //        StartDate = "2022-12",
            //        Teams = 8
            //    });
            //}
            //return View(t);

            var t = new List<Trophy>();

            String constr = "Data Source=LDW-LAP;Initial Catalog=ESPORTS;Integrated Security=True";

            using (SqlConnection connection = new SqlConnection(constr))
            {
                connection.Open();
                String sql = "SELECT * FROM Trophy";

                using (SqlCommand command = new SqlCommand(sql, connection))
                {
                    using (SqlDataReader reader = command.ExecuteReader())
                    {
                        while (reader.Read())
                        {
                            Trophy tro = new Trophy();
                            tro.ID = reader.GetInt32(0);
                            tro.Name = reader.GetString(1);
                            tro.StartDate = reader.GetDateTime(2).ToString();
                            tro.EndDate = reader.GetDateTime(3).ToString();
                            tro.Teams = reader.GetInt32(4);

                            t.Add(tro);
                        }
                    }
                }
            }

            return View(t);
        }

        [HttpPost]
        public IActionResult CreateNewTrophy()
        {
            //Console.WriteLine("SignIn", signIn.UserName, signIn.Email, signIn.Password, signIn.PhoneNumber);
            //return View();

            //connectionString();
            //con.Open();
            //com.Connection = con;
            //com.CommandText = "INSERT INTO Admin (user_name, password, email, phone_number) VALUES ('" + signIn.UserName + "', '" + signIn.Password + "', '" + signIn.Email + "', '" + signIn.PhoneNumber + "') ";
            //dr = com.ExecuteReader();
            //con.Close();
            return View();
        }

        [HttpPost]
        public IActionResult CreateANewTrophy(Trophy trophy)
        {
            connectionString();
            con.Open();
            com.Connection = con;
            com.CommandText = "INSERT INTO Trophy (trophy_name, start_date, end_date, teams) VALUES ('" + trophy.Name + "', '" + trophy.StartDate + "', '" + trophy.EndDate + "', '" + trophy.Teams + "') ";
            dr = com.ExecuteReader();
            con.Close();
            return View("CreateTrophy");
        }

        public IActionResult EditTrophy()
        {
            return View();
        }

        public IActionResult DeleteTrophy()
        {
            return View();
        }

        public IActionResult PlayerRegistration()
        {

            var player = new List<Player>();

            String constr = "Data Source=LDW-LAP;Initial Catalog=ESPORTS;Integrated Security=True";

            using (SqlConnection connection = new SqlConnection(constr))
            {
                connection.Open();
                String sql = "SELECT * FROM Player WHERE status = 0";

                using (SqlCommand command = new SqlCommand(sql, connection))
                {
                    using (SqlDataReader reader = command.ExecuteReader())
                    {
                        while (reader.Read())
                        {
                            Player p = new Player();
                            p.ID = reader.GetInt32(0);
                            p.FirstName = reader.GetString(1);
                            p.Email = reader.GetString(2);
                            p.BasePrice = reader.GetInt32(3).ToString();
                            p.Status = reader.GetInt32(4);
                            p.TrophyRegistered = reader.GetString(5);
                            //p.TrophyRegistered = reader.GetString(3);

                            player.Add(p);
                        }
                    }
                }
            }

            return View("PlayerRegistrationProcess", player);
        }

        public IActionResult EditPlayerBasePrice(int id, string FirstName)
        {
            return View();
        }

        public IActionResult SaveEditedPlayerBasePrice(Player player)
        {
            //Console.WriteLine(player);

            connectionString();
            con.Open();
            com.Connection = con;
            com.CommandText = "UPDATE Player SET baseprice = '"+player.BasePrice+ "', status = 1 WHERE id = '" + player.ID+"' ";
            dr = com.ExecuteReader();
            con.Close();
            return View();
        }

        public IActionResult AuctionList()
        {
            var playerAuction = new List<PlayerAuction>();

            String constr = "Data Source=LDW-LAP;Initial Catalog=ESPORTS;Integrated Security=True";

            using (SqlConnection connection = new SqlConnection(constr))
            {
                connection.Open();
                String sql = "SELECT * FROM Auction";

                using (SqlCommand command = new SqlCommand(sql, connection))
                {
                    using (SqlDataReader reader = command.ExecuteReader())
                    {
                        while (reader.Read())
                        {
                            PlayerAuction p = new PlayerAuction();
                            p.ID = reader.GetInt32(0);
                            p.AuctionName = reader.GetString(1);
                            p.StartDate = reader.GetDateTime(2).ToString();
                            p.EndDate = reader.GetDateTime(3).ToString();

                            playerAuction.Add(p);
                        }
                    }
                }
            }
            return View(playerAuction);2..jh
        }

        public IActionResult CreateAuction()
        {
            return View();
        }

        public IActionResult CreateNewAuction(PlayerAuction playerAuction)
        {
            connectionString();
            con.Open();
            com.Connection = con;
            com.CommandText = "INSERT INTO Auction (auctionName, startDate, endDate) VALUES ('" + playerAuction.AuctionName + "', '" + playerAuction.StartDate + "', '" + playerAuction.EndDate + "') ";
            dr = com.ExecuteReader();
            con.Close();

Controllers/Teamowner/TeamOwnerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Data.SqlClient;
using Microsoft.AspNetCore.Mvc;
using AD.Models.Teamowner;
using Microsoft.AspNetCore.Http;
using System.Data;


namespace AD.Controllers.Teamowner
{
    public class TeamOwnerController : Controller
    {
        SqlConnection con = new SqlConnection();
        SqlCommand com = new SqlCommand();
        SqlDataReader dr;

        string Str = @"Data Source=LDW-LAP;Initial Catalog=ESPORTS;Integrated Security=True";

        void connectionString()
        {
            con.ConnectionString = "Data Source=LDW-LAP;Initial Catalog=ESPORTS;Integrated Security=True";
        }




        // GET: TeamOwnerController
        public ActionResult Index()
        {
            return View();
        }

        //Player Login
        [HttpGet]
        public IActionResult TeamOwnerLogin()
        {
            return View();
        }


        //Player verify (login)
        [HttpPost]
        public IActionResult TeamOwnerLogin(Teamow teamlog)
        {
            Teamow obj = new Teamow();
            connectionString();
            con.Open();
            com.Connection = con;
            com.CommandText = "select * from TeamOwner where teamow_email='" + teamlog.teamow_email + "' and password = '" + teamlog.password + "' ";
            dr = com.ExecuteReader();
            if (dr.Read())
            {
                con.Close();
                return View("Index");
            }
            else
            {
                con.Close();
                ViewData["message"] = "Email or Password incorrect!";
            }
            return View();
        }

        // GET: TeamOwnerController/Details/5 (view)
        public ActionResult Details(int id)
        {
            var teamowlist = new List<Teamow>();

            String constr = "Data Source=LDW-LAP;Initial Catalog=ESPORTS;Integrated Security=True";

            using (SqlConnection connection = new SqlConnection(constr))
            {
                connection.Open();
                String sql = "SELECT * FROM TeamOwner";

                using (SqlCommand command = new SqlCommand(sql, connection))
                {
                    using (SqlDataReader reader = command.ExecuteReader())
                    {
                        while (reader.Read())
                        {
                            Teamow tmo = new Teamow();
                            tmo.teamow_id = reader.GetInt32(0);
                            tmo.teamow_name = reader.GetString(1);
                            tmo.team_name = reader.GetString(2);
                            tmo.teamow_email = reader.GetString(3);
                            tmo.teamow_contact = reader.GetString(4);


                            teamowlist.Add(tmo);
                        }
                    }
                }
            }

            return View(teamowlist);
        }
    

        // GET: TeamOwnerController/Create
        public ActionResult TeamowCreate()
        {
            return View(new Teamow());
        }

        // POST: TeamOwnerController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult TeamowCreate(Teamow teamo)
        {
            try
            {
                using (SqlConnection con = new SqlConnection(Str))
                {
                    con.Open();
                    string q = "INSERT INTO TeamOwner VALUES ('" + teamo.teamow_name + "', '" + teamo.team_name + "', '" + teamo.teamow_email + "', '" + teamo.teamow_contact + "', '" + teamo.password + "')";
                    SqlCommand cmd = new SqlCommand(q, con);
                    cmd.ExecuteNonQuery();
                }

                return RedirectToAction("Details");
            }
            catch
            {
                return View();
            }
        }

        // GET: TeamOwnerController/Edit/5
        public ActionResult Edit(int id)
        {

            Teamow teamo = new Teamow();
            DataTable dataTable = new DataTable();
            using (SqlConnection con = new SqlConnection(Str))
            {
                con.Open();
                string q = "SELECT * FROM TeamOwner WHERE teamow_id=" + id;
                SqlDataAdapter da = new SqlDataAdapter(q, con);
                da.Fill(dataTable);
            }
            if (dataTable.Rows.Count == 1)
            {
                teamo.teamow_id = Convert.ToInt32(dataTable.Rows[0][0].ToString());
                teamo.teamow_name = dataTable.Rows[0][1].ToString();
                teamo.team_name = dataTable.Rows[0][2].ToString();
                teamo.teamow_email = dataTable.Rows[0][3].ToString();
                teamo.teamow_contact = dataTable.Rows[0][4].ToString();
                teamo.password = dataTable.Rows[0][5].ToString();
                return View(teamo);

            }
            return RedirectToAction("Details");
        }


        // POST: TeamOwnerController/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, Teamow teamo)
        {
            using (SqlConnection con = new SqlConnection(Str))
            {
                con.Open();
                string q = "UPDATE TeamOwner SET teamow_name=@teamow_name,team_name=@team_name,teamow_email=@teamow_email,teamow_contact=@teamow_contact,password=@password WHERE teamow_id=@id";
                SqlCommand cmd = new SqlCommand(q, con);

                cmd.Parameters.AddWithValue("@id", teamo.teamow_id);
                cmd.Parameters.AddWithValue("@teamow_name", teamo.teamow_name);
                cmd.Parameters.AddWithValue("@team_name", teamo.team_name);
                cmd.Parameters.AddWithValue("@teamow_email", teamo.teamow_email);
                cmd.Parameters.AddWithValue("@teamow_contact", teamo.teamow_contact);
                cmd.Parameters.AddWithValue("@password", teamo.password);

                cmd.ExecuteNonQuery();
            }

            return RedirectToAction("Details");
        }





        // GET: TeamOwnerController/Delete/5
        public ActionResult Delete(int id)
        {
            connectionString();
            con.Open();
            string query = "DELETE FROM TeamOwner WHERE teamow_id = @id ";
            SqlCommand cmd = new SqlCommand(query, con);
            cmd.Parameters.AddWithValue("@id", id);
            cmd.ExecuteNonQuery();

            return RedirectToAction("Details");
        }

        // POST: TeamOwnerController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Views/AdminLogin/AddTeamBasePrice.cshtml
@{
    ViewData["Title"] = "AddTeamBasePrice";
}

<h1 class="mt-5 text-white">Team Base Price Updated</h1>

<p>
    <a asp-action="Dashboard">Back</a>
</p>

Views/AdminLogin/AuctionList.cshtml
@model IEnumerable<AD.Models.Admin.PlayerAuction>

@{
    ViewData["Title"] = "AuctionList";
}

<h1 class="mt-5 text-white">Auction List</h1>

<p>
    <a asp-action="CreateAuction" class="btn btn-primary">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th class="text-white">
                @Html.DisplayNameFor(model => model.ID)
            </th>
            <th class="text-white">
                @Html.DisplayNameFor(model => model.AuctionName)
            </th>
            <th class="text-white">
                @Html.DisplayNameFor(model => model.StartDate)
            </th>
            <th class="text-white">
                @Html.DisplayNameFor(model => model.EndDate)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td class="text-white">
                @Html.DisplayFor(modelItem => item.ID)
            </td>
            <td class="text-white">
                @Html.DisplayFor(modelItem => item.AuctionName)
            </td>
            <td class="text-white">
                @Html.DisplayFor(modelItem => item.StartDate)
            </td>
            <td class="text-white">
                @Html.DisplayFor(modelItem => item.EndDate)
            </td>
            <td class="text-white">
                @*@Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })*@
                <form action="AddPlayersToTeams" method="post">
                    <input type="hidden" name="id" value="@Html.DisplayFor(modelItem => item.ID)" id="form2Example1" class="form-control" />
                    <button class="btn btn-warning">
                        Edit
                    </button>
                </form>
            </td>
        </tr>
}
    </tbody>
</table>

<div>
    <a asp-action="Dashboard">Back</a>
</div>

Views/AdminLogin/CreateAdmin.cshtml
@{
    ViewData["Title"] = "CreateAdmin";
}

<div class="container mt-5 ">
    <h1 class="mt-5 text-white">ADMIN CREATION</h1>

    <form action="CreateNewAdmin" method="post">
        <!-- User input -->
        <div class="form-outline mb-4">
            <label class="form-label text-white" for="form2Example1">User Name</label>
            <input type="text" name="UserName" id="form2Example1" class="form-control" required/>
        </div>

        <!-- Email input -->
        <div class="form-outline mb-4">
            <label class="form-label text-white" for="form2Example1">Email address</label>
            <input type="text" name="Email" id="form2Example1" class="form-control" required/>
        </div>

        <!-- Password input -->
        <div class="form-outline mb-4">
            <label class="form-label text-white" for="form2Example2">Password</label>
            <input type="password" name="Password" id="form2Example2" class="form-control" required/>
        </div>

        <!-- Phone Number input -->
        <div class="form-outline mb-4">
            <label class="form-label text-white" for="form2Example2">Phone Number</label>
            <input type="text" name="PhoneNumber" id="form2Example2" class="form-control" required/>
        </div>

        <!-- Submit button -->
        <input type="submit" value="Create New Admin" class="btn btn-primary"/>
    </form>
</div>

<div>
    <a asp-action="Dashboard">Back</a>
</div>

Views/AdminLogin/CreateAuction.cshtml
@model AD.Models.Admin.PlayerAuction

@{
    ViewData["Title"] = "CreateAuction";
}

<h1 class="mt-5 text-white">Create Auction</h1>

@*<h4>PlayerAuction</h4>*@
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="CreateNewAuction">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ID" class="control-label text-white" hidden></label>
                <input asp-for="ID" class="form-control" hidden/>
                <span asp-validation-for="ID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AuctionName" class="control-label text-white"></label>
                <input asp-for="AuctionName" class="form-control" required/>
                <span asp-validation-for="AuctionName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StartDate" class="control-label text-white"></label>
                <input asp-for="StartDate" class="form-control" required/>
                <span asp-validation-for="StartDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EndDate" class="control-label text-white"></label>
                <input asp-for="EndDate" class="form-control" required/>
                <span asp-validation-for="EndDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="AuctionList">Back to List</a>
</div>

Views/AdminLogin/CreateNewTrophyV1.cshtml
@model IEnumerable<AD.Models.Admin.Trophy>

@{
    ViewData["Title"] = "CreateNewTrophyV1";
}

<h1 class="mt-5 text-white">Trophies</h1>

<p>
    @*<a asp-action="CreateNewTrophy">Create New</a>*@
    <form action="CreateNewTrophy" method="post">
        <input type="submit" value="Create Trophy" class="btn btn-success"/>
    </form>
</p>
<table class="table">
    <thead>
        <tr>
            <th class="text-white">
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th class="text-white">
                @Html.DisplayNameFor(model => model.StartDate)
            </th>
            <th class="text-white">
                @Html.DisplayNameFor(model => model.EndDate)
            </th>
            <th class="text-white">
                @Html.DisplayNameFor(model => model.Teams)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td class="text-white">
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td class="text-white">
                @Html.DisplayFor(modelItem => item.StartDate)
            </td>
            <td class="text-white">
                @Html.DisplayFor(modelItem => item.EndDate)
            </td>
            <td class="text-white">@*  *@
                @Html.DisplayFor(modelItem => item.Teams)
            </td>
            <td class="text-white">
                <form action="DeleteT" method="post">
                    <input type="hidden" name="id" value="@Html.DisplayFor(modelItem => item.ID)" id="form2Example1" class="form-control" />
                    <button class="btn btn-danger">
                        Delete
                    </button>
                </form>
                @*@Html.ActionLink("Edit", "EditTrophy", new { id = item.ID }) |
                @@Html.ActionLink("Details", "Details", new {  id=item.PrimaryKey  }) |
                @Html.ActionLink("Delete", "DeleteTrophy", new { })*@
            </td>
        </tr>
}
    </tbody>
</table>

<div>
    <a asp-action="Dashboard">Back</a>
</div>

Views/AdminLogin/CreateTrophy.cshtml
@{
    ViewData["Title"] = "CreateTrophy";
}

<h1 class="mt-5 text-white">Create Trophy</h1>

@*trouphy list, add, edit, delete*@

<form action="CreateNewTrophy" method="post">
    <input type="submit" value="Create Trophy" />
</form>

Views/AdminLogin/Dashboard.cshtml
@{
    ViewData["Title"] = "Dashboard";
}

<style>
    #icon {
        margin-top: 20px;
        font-size: 50px;
        color: #0026ff;
    }

        #icon:hover {
            color: red;
            font-size: 60px;
        }

    .card {
        margin-bottom: 25px;
    }
</style>
<script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/js/all.min.js" integrity="sha512-F5QTlBqZlvuBEs9LQPqc1iZv2UMxcVXezbHzomzS6Df4MZMClge/8+gXrKw2fl5ysdk4rWjR0vKS7NNkfymaBQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
@*<h1>Dashboard</h1>

    <button>Create New Admin</button>*@

<div class="container mt-5 ">
    <h1 class="text-center text-white m-5">Admin Dashboard</h1>

    @*<form action="CreateAdmin" method="post">
            <input type="submit" class="btn btn-secondary btn-lg" value="Create New Admin" />
        </form>

        <form action="CreateNewTrophyV1" method="post">
            <input type="submit" class="btn btn-secondary btn-lg" value="Trophy" />
        </form>*@

    <div class="container px-4 text-center">
        <div class="row gx-5">

            <div class="col-lg-3">
                <div class="card" style="height: 200px;">
                    <div class="card-body">
                        <h2 style="text-align: center;">Create New Admin</h2>
                        <div style="text-align: center;">
                            <a class="navbar-brand" asp-area="" asp-controller="AdminLogin" asp-action="CreateAdmin"><i id="icon" class="fa fa-user"></i></a>
                        </div>
                    </div>
                </div>
            </div>

            @*<div class="col">
        <form action="CreateAdmin" method="post">
            <input type="submit" class="btn btn-secondary btn-lg" value="Create New Admin" />
        </form>
        </div>*@

            @*<div class="col-lg-3">
                <div class="card" style="height: 200px;">
                    <div class="card-body">
                        <h2 style="text-align: center;">Create New Admin</h2>
                        <div style="text-align: center;">
                            <a class="navbar-brand" asp-area="" asp-controller="AdminLogin" asp-action="CreateNewTrophyV1"><i id="icon" class="fa fa-user"></i></a>
                        </div>
                    </div>
                </div>
            </div>*@

            @*<div class="col">
            <form action="CreateNewTrophyV1" method="post">
                <input type="submit" class="btn btn-secondary btn-lg" value="Trophy" />
            </form>
        </div>*@

            <div class="col-lg-3">
                <div class="card" style="height: 200px;">
                    <div class="card-body">
                        <h2 style="text-align: center;">Auction</h2>
                        <div style="text-align: center;">
                            <a class="navbar-brand" asp-area="" asp-controller="AdminLogin" asp-action="AuctionList"><i id="icon" class="fa fa-user"></i></a>
                        </div>
                    </div>
                </div>
            </div>

            @*<div class="col">
            <form action="AuctionList" method="post">
                <input type="submit" class="btn btn-secondary btn-lg" value="Auction" />
            </form>
        </div>*@

            <div class="col-lg-3">
                <div class="card" style="height: 200px;">
                    <div class="card-body">
                        <h2 style="text-align: center;">Player Registration</h2>
                        <div style="text-align: center;">
                            <a class="navbar-brand" asp-area="" asp-controller="AdminLogin" asp-action="PlayerRegistration"><i id="icon" class="fa fa-user"></i></a>
                        </div>
                    </div>
                </div>
            </div>

            @*<div class="col">
            <form action="PlayerRegistration" method="post">
                <input type="submit" class="btn btn-secondary btn-lg" value="Player Registration" />
            </form>
        </div>*@

            <div class="col-lg-3">
                <div class="card" style="height: 200px;">
                    <div class="card-body">
                        <h2 style="text-align: center;">Team Registration</h2>
                        <div style="text-align: center;">
                            <a class="navbar-brand" asp-area="" asp-controller="AdminLogin" asp-action="TeamRegistration"><i id="icon" class="fa fa-user"></i></a>
                        </div>
                    </div>
                </div>
            </div>
            </div>
            <div class="row gx-5">
             <div class="col-lg-3">
                <div class="card" style="height: 200px;">
                    <div class="card-body">
                        <h2 style="text-align: center;">View Players</h2>
                        <div style="text-align: center;">
                            <a class="navbar-brand" asp-area="" asp-controller="NewPlayers" asp-action="PlayerList"><i id="icon" class="fa fa-user"></i></a>
                        </div>
                    </div>
                </div>
            </div>

             <div class="col-lg-3">
                <div class="card" style="height: 200px;">
                    <div class="card-body">
                        <h2 style="text-align: center;">View Team Owner</h2>
                        <div style="text-align: center;">
                            <a class="navbar-brand" asp-area="" asp-controller="TeamOwner" asp-action="Details"><i id="icon" class="fa fa-user"></i></a>
                        </div>
                    </div>
                </div>
            </div>

            </div>
    </div>
</div>

Views/AdminLogin/DeleteT.cshtml
@{
    ViewData["Title"] = "DeleteT";
}

<h1 class="mt-5 text-white">Deleted Trophy Successfully</h1>

<div>
    <a asp-action="Dashboard">Back</a>
</div>

Views/AdminLogin/SavePlayerBuy.cshtml
@{
    ViewData["Title"] = "SavePlayerBuy";
}

<h1 class="mt-5 text-white">Player Saved</h1>

<div>
    <a asp-action="AuctionList">Back</a>
</div>